local o = vim.opt
o.cmdheight = 0
o.number = true
o.relativenumber = false
o.mouse = ""
o.conceallevel = 1
o.cursorline = false
o.tabstop = 2
o.shiftwidth = 2
o.expandtab = true
o.autoindent = true
o.termguicolors = true
o.clipboard = "unnamedplus"
o.undofile = true
vim.g.mapleader = " "
